

from django import views
from django.urls import path
from .views import*
from .views import approve_course
from .views import hide_course
from .views import monthly_earning_view


urlpatterns = [
    # path('teacher_home', home,name="teacher_home"),
    path('wallet_details', WalletDetails,name="wallet_details"),
    path('makePayoutRequest', MakePayoutRequest,name="makePayoutRequest"),
    path('addBank', AddBank,name="addBank"),
    path('deleteBank/<uuid:id>', DeleteBank,name="deleteBank"),
    path('not_foundt', NotFoundView,name="not_foundt"),
    path('add_module', AddCourseModule,name="add_module"),
    path('add_course', AddCourse,name="add_course"),
    path('update_course/<int:id>', UpdateCourse,name="update_course"),
    path('show_course', ShowCourse,name="show_course"),
    path('hide_course', HideCourse,name="hide_course"),
    path('delete_course/<int:id>', DeleteCourse,name="delete_course"),
    # path('course_list/<int:id>', CourseList,name="course_list"),
    path('course-list/<int:id>/', CourseList, name='course_list'),
    path('get_course', GetCourse,name="get_course"),
    path('add_chapter/<int:id>', AddChapter,name="add_chapter"),
    path('update_chapter/<int:id>', UpdateChapter,name="update_chapter"),
    path('get_chapter', GetChapter,name="get_chapter"),
    path('chapter_list/<int:id>', ChapterList,name="chapter_list"),
    path('show_chapter', ShowChapter,name="show_chapter"),
    path('hide_chapter', HideChapter,name="hide_chapter"),
    path('delete_chapter', DeleteChapter,name="delete_chapter"),
    path('delete_topic', DeleteTopic,name="delete_topic"),
    path('create_course_review/<int:id>', CreateCourseReview,name="create_course_review"),
    path('update_course_review/<int:id>', UpdateCourseReview,name="update_course_review"),
    path('update_course_reviews/<int:id>', UpdateCourseReview1,name="update_course_reviews"),
    path('delete_course_review/<int:rid>', DeleteCourseReview,name="delete_course_review"),
    path('live_course/<int:id>', Live_Course,name="live_course"),
    path('live_course_update/<int:id>', LiveCourseUpdate,name="live_course_update"),
    path('add_live_course', AddLiveCourse,name="add_live_course"),
    path('delete_course_live/<int:id>', DeleteCourseLive,name="delete_course_live"),
    path('admin/approve_course/', approve_course, name='approve_course'),
    path('admin/hide_course/', hide_course, name='hide_course'),
    path('course/<int:course_id>/', course_detail, name='course_detail'),
    path('monthly-earning/', monthly_earning_view, name='monthly_earning'),
    path('yearly-earning/', yearly_earning_view, name='yearly_earning'),
    path('course_chapter/<int:course_id>/', course_chapter, name='course_chapter'),
    path('ChapterTopicList/<int:id>',ChapterTopicList,name="ChapterTopicList"),
    path('chapter_assignments/<int:chapter_id>/<int:topic_id>/', chapter_assignments, name='chapter_assignments'),
    path('chapter_quizzes/<int:chapter_id>/<int:topic_id>/', chapter_quizzes, name='chapter_quizzes'),
    path('super_admin/purchased_courses/<int:user_id>/', super_admin_purchased_courses, name='super_admin_purchased_courses'),
    
    path('add_topic/<int:id>', AddTopic,name="add_topic"),
    path('get_topic', GetTopic,name="get_topic"),
    path('topic_list/<int:id>', TopicList,name="topic_list"),
    path('add_topic_video/<int:id>', AddTopicVideo,name="add_topic_video"),
    path('add_topic_video_json', AddTopicVideoJson,name="add_topic_video_json"),
    path('course_feedback_list/<int:id>', CourseFeedbackList,name="course_feedback_list"),
    path('course_statistics', CourseStatistics,name="course_statistics"),
    path('createInvoice/<int:id>', CreateInvoice,name="createInvoice"),
    path('planning', Planning,name="planning"),
    path('course/students/<int:id>', CourseStudentList,name="course_students_list"),
    path('view_profile', viewProfile,name="view_profile"),
    path('uploadProfileImage', uploadProfileImage,name="uploadProfileImage"),
    path('uploadProfile', uploadProfile,name="uploadProfile"),
    path('import_users', import_users,name="import_users"),
    path('add_single_user', addSingleUser,name="add_single_user"),
    path('get_imported_users/<int:id>', get_imported_users,name="get_imported_users"),
    path('approveAllUsers', ApproveAllUsers,name="approveAllUsers"),
    path('deleteAllUsers', DeleteAllUsers,name="deleteAllUsers"),
    path('update-kyc/', update_kyc_details, name='update_kyc_details'),
    path('update-education/', update_education_details, name='update_education_details'),
    path('update_bank/', update_bank_details, name='update_bank_details'),
   
    # Quiz Urls
    path('quiz/create', create_quiz, name="create_quiz"),
    path('quiz/<str:code>/edit', edit_quiz, name="edit_quiz"),
    path('quiz/<str:code>/edit_quiz_title', edit_quiz_title, name="edit_quiz_title"),
    path('quiz/<str:code>/edit_quiz_description', edit_quiz_description, name="edit_quiz_description"),
    path('quiz/<str:code>/edit_quiz_question', edit_quiz_question, name="edit_quiz_question"),
    path('quiz/<str:code>/edit_quiz_choice', edit_quiz_choice, name="edit_quiz_choice"),
    path('quiz/<str:code>/add_quiz_choice', add_quiz_choice, name="add_quiz_choice"),
    path('quiz/<str:code>/remove_quiz_choice', remove_quiz_choice, name="remove_quiz_choice"),
    path('quiz/<str:code>/add_quiz_question', add_quiz_question, name="add_quiz_question"),
    path('quiz/<str:code>/delete_quiz_question/<str:question>', delete_quiz_question, name="delete_quiz_question"),
    path('quiz/<str:code>/edit_quiz_score', edit_quiz_score, name="edit_quiz_score"),
    path('quiz/<str:code>/quiz_answer_key', quiz_answer_key, name="quiz_answer_key"),
    path('quiz/<str:code>/quiz_responses', quiz_responses, name='quiz_responses'),
    path('quiz/<str:code>/single_response/<str:response_code>', single_response, name="single_response"),
    path('quiz/<str:code>/edit_score', edit_score, name="edit_score"),
    # custom form urls
    path('form/create', create_form, name="create_form"),
    path('form/<str:code>/edit', edit_form, name="edit_form"),
    path('form/<str:code>/edit_title', edit_title, name="edit_title"),
    path('form/<str:code>/edit_description', edit_description, name="edit_description"),
    path('form/<str:code>/edit_background_color', edit_bg_color, name="edit_background_color"),
    path('form/<str:code>/edit_text_color', edit_text_color, name="edit_text_color"),
    path('form/<str:code>/edit_setting', edit_setting, name="edit_setting"),
    path('form/<str:code>/delete', delete_form, name="delete_form"),
    path('form/<str:code>/edit_question', edit_question, name="edit_question"),
    path('form/<str:code>/edit_choice', edit_choice, name="edit_choice"),
    path('form/<str:code>/add_choice', add_choice, name="add_choice"),
    path('form/<str:code>/remove_choice', remove_choice, name="remove_choice"),
    path('form/<str:code>/get_choice/<str:question>', get_choice, name="get_choice"),
    path('form/<str:code>/add_question', add_question, name="add_question"),
    path('form/<str:code>/delete_question/<str:question>', delete_question, name="delete_question"),
    path('form/<str:code>/score', score, name="score"),
    # path('form/<str:code>/edit_score', edit_score, name="edit_score"),
    path('form/<str:code>/answer_key', answer_key, name="answer_key"),
    path('form/<str:code>/feedback', feedback, name="feedback"),
    path('form/<str:code>/preview_form', preview_form, name="preview_form"),
    path('form/<str:code>/viewform', view_form, name="view_form"),
    path('form/<str:code>/submit', submit_form, name="submit_form"),
    path('form/<str:code>/responses', responses, name='responses'),
    path('form/<str:code>/response/<str:response_code>', response, name="response"),
    path('form/<str:code>/response/<str:response_code>/edit', edit_response, name="edit_response"),
    path('form/<str:code>/responses/delete', delete_responses, name="delete_responses"),
    path('form/<str:code>/export_csv', exportcsv,name='export_csv'),


    path('calendar', CalendarView.as_view(), name='calendar'),
    path('event/new', event, name='event_new'),
    path('event/edit/<event_id>', event, name='event_edit'),
    path('event/delete/<event_id>', deleteEvent, name='event_delete'),
]
