# Generated by Django 4.2 on 2023-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_discount',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
