# Generated by Django 4.2 on 2023-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_assignment',
            field=models.FileField(blank=True, null=True, upload_to='topic_resources'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_video',
            field=models.FileField(blank=True, null=True, upload_to='topic_resources'),
        ),
    ]
