# Generated by Django 4.2 on 2023-10-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_topicquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_assignment',
        ),
        migrations.CreateModel(
            name='TopicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='topic_resources')),
                ('text', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_assignment', to='teacher.topic')),
            ],
        ),
    ]
