# Generated by Django 4.2 on 2023-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_topic_topic_assignment_topicassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicassignment',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Time', 'Time'), ('File', 'File'), ('Image', 'Image'), ('Pdf', 'Pdf')], max_length=20),
        ),
    ]
