# Generated by Django 4.2 on 2023-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_topicassignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='topicassignment',
            name='type',
        ),
        migrations.AddField(
            model_name='topicassignment',
            name='type',
            field=models.ManyToManyField(related_name='assignment_type', to='teacher.assignmenttype'),
        ),
    ]
