# Generated by Django 4.2 on 2023-10-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_assignmenttype_remove_topicassignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
