# Generated by Django 4.2 on 2023-10-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_answer_choices_form_responses_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='topic',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='teacher.topic'),
            preserve_default=False,
        ),
    ]
