# Generated by Django 4.2 on 2023-10-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_form_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_valid_date',
            new_name='coupon_valid_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_valid_time',
            new_name='coupon_valid_time',
        ),
    ]
