# Generated by Django 4.2 on 2023-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_rename_course_valid_date_course_coupon_valid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='actual_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='generated_coupon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_discount',
            field=models.CharField(blank=True, default=0.0, max_length=100, null=True),
        ),
    ]
