# Generated by Django 4.2 on 2023-10-30 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_alter_course_actual_fee_alter_course_discount_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
