# Generated by Django 4.2 on 2023-11-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_purchasedcourse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='plateform',
            field=models.CharField(default='Website', max_length=200),
        ),
    ]
