# Generated by Django 4.2 on 2023-11-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_purchasedcourse_plateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_assignments', to='teacher.topic'),
        ),
    ]
