# Generated by Django 4.2 on 2023-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_file'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_file'),
        ),
    ]
