# Generated by Django 4.2 on 2023-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_course_schedule_date_course_schedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
