# Generated by Django 4.2 on 2023-11-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
