# Generated by Django 4.2 on 2023-11-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_course_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
