# Generated by Django 4.2 on 2023-11-21 05:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_chapter_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
