# Generated by Django 4.2 on 2023-11-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_alter_chapter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicassignment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicassignment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='topicquiz',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AssignmentType',
        ),
        migrations.DeleteModel(
            name='TopicAssignment',
        ),
        migrations.DeleteModel(
            name='TopicQuiz',
        ),
    ]
