# Generated by Django 4.2 on 2023-11-27 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0032_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
