# Generated by Django 4.2 on 2023-11-27 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0033_course_wishlist_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
