# Generated by Django 4.2 on 2023-12-18 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0035_coursequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='course_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
