# Generated by Django 4.2 on 2023-12-18 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0038_chapter_progress_course_progress_topic_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='course',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='progress',
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(blank=True, default=0.0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='teacher.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
