# Generated by Django 4.2 on 2023-12-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0040_alter_courseprogress_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='teacher.course', unique=True),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
