# Generated by Django 4.2 on 2023-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0042_topicprogress_chapterprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-rating']},
        ),
    ]
