# Generated by Django 4.2 on 2023-12-22 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0043_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupon_applied_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_applied_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='coupon_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
