# Generated by Django 4.2 on 2023-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0044_course_coupon_applied_by_course_coupon_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
