# Generated by Django 4.2 on 2023-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0045_coursecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
