# Generated by Django 4.2 on 2024-01-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0046_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='teacher.course'),
        ),
    ]
