# Generated by Django 4.2 on 2024-01-01 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0047_alter_courseprogress_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='teacher.chapter'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='teacher.topic'),
        ),
    ]
