# Generated by Django 4.2 on 2024-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0048_alter_chapterprogress_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='order_id',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
