# Generated by Django 4.2 on 2024-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0050_language_remove_course_language_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coupon_percent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
