# Generated by Django 4.2 on 2024-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0051_alter_course_coupon_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(blank=True, to='teacher.language'),
        ),
    ]
