# Generated by Django 4.2 on 2024-02-05 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0055_course_about_host_course_fees_course_host_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=False, max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('about_host', models.TextField()),
                ('host_name', models.CharField(max_length=200)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='live_course_file')),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_course_category', to='teacher.coursecategory')),
                ('language', models.ManyToManyField(blank=True, null=True, to='teacher.language')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='live_user_course', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='live_course_wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
