# Generated by Django 4.2 on 2024-02-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0056_livecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecourse',
            name='language',
        ),
    ]
