# Generated by Django 4.2 on 2024-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0057_remove_livecourse_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
