# Generated by Django 4.2 on 2024-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0059_alter_course_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='profile',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='LiveCourse',
        ),
    ]
