# Generated by Django 4.2 on 2024-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0061_alter_course_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hide',
        ),
    ]
