# Generated by Django 4.2 on 2024-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0062_remove_course_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
