# Generated by Django 4.2 on 2024-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0063_course_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
