# Generated by Django 4.2 on 2024-02-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0067_certificate_course_alter_certificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
