# Generated by Django 4.2 on 2024-02-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_hitcount_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='type',
            field=models.CharField(default='DefaultType', max_length=100),
        ),
    ]
