# Generated by Django 4.2 on 2024-02-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0069_purchasedcourse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedcourse',
            name='type',
        ),
    ]
