# Generated by Django 4.2 on 2024-03-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0070_remove_purchasedcourse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitcount',
            name='hit_count',
        ),
    ]
