# Generated by Django 4.2 on 2024-03-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0071_remove_hitcount_hit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitcount_set', to='teacher.course'),
        ),
    ]
