# Generated by Django 4.2 on 2024-03-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0072_alter_hitcount_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
    ]
