# Generated by Django 4.2 on 2023-10-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_purchasedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
