# Generated by Django 4.2 on 2023-10-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membership_usermembership_subscription_payhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Enterprise', 'Enterprise'), ('Advanced', 'Advanced'), ('Basic', 'Basic'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
