# Generated by Django 4.2 on 2023-10-31 07:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=tinymce.models.HTMLField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
