# Generated by Django 4.2 on 2023-11-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscription_created_at_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plateform',
            field=models.CharField(default='Website', max_length=200),
        ),
    ]
