# Generated by Django 4.2 on 2023-11-02 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
