# Generated by Django 4.2 on 2023-11-02 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_banks_user_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='transaction id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancel', 'Cancel'), ('decline', 'Decline'), ('fail', 'Fail')], default='pending', max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('payout', 'Payout Wallet'), ('debit', 'Debit Wallet'), ('credit', 'Credit Wallet')], default='payout', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
        ),
    ]
