# Generated by Django 4.2 on 2023-11-04 07:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0016_wallettransaction_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intrest_area',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
