# Generated by Django 4.2 on 2023-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
