# Generated by Django 4.2 on 2023-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_facebook_link_customuser_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
