# Generated by Django 4.2 on 2023-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_steps',
            field=models.IntegerField(default=0),
        ),
    ]
