# Generated by Django 4.2 on 2023-12-16 10:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_supportquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Percent', 'Percent'), ('Price', 'Price')], default='Percent', max_length=100)),
                ('rate', models.IntegerField()),
                ('description', models.TextField()),
                ('terms', tinymce.models.HTMLField()),
            ],
        ),
    ]
