# Generated by Django 4.2 on 2023-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=500, null=True)),
                ('title_2', models.CharField(blank=True, max_length=500, null=True)),
                ('title_3', models.CharField(blank=True, max_length=500, null=True)),
                ('title_4', models.CharField(blank=True, max_length=500, null=True)),
                ('title_5', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sub_title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
