# Generated by Django 4.2 on 2023-12-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_slider_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='type',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
