# Generated by Django 4.2 on 2024-01-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_slider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='type',
            field=models.CharField(max_length=500),
        ),
    ]
