# Generated by Django 4.2 on 2024-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='privacy_images/'),
        ),
    ]
