# Generated by Django 4.2 on 2024-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_privacypolicy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='terms_images/'),
        ),
    ]
