# Generated by Django 4.2 on 2024-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_termsandcondition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_4',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
