"""
Django settings for Sphurit project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = 'user_login'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&&$stf#d@me!g!63-+aify%!@_+9kum&5=ng!l96m7=98d*3v!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# import socket

# s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
# s.connect(("8.8.8.8", 80))
# ,s.getsockname()[0],
ALLOWED_HOSTS = ["localhost", "*"]

# Application definition

INSTALLED_APPS = [
    'admin_datta.apps.AdminDattaConfig',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    #third party app
    'tinymce',
    'taggit',
    'corsheaders',
    'rest_framework',
    'django_extensions',
    'ckeditor',
    #custom app
    'core.apps.CoreConfig',
    'teacher',
    'chats.apps.ChatsConfig',
]
AUTH_USER_MODEL = "core.CustomUser"
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'Sphurit.middleware.HtmxMessageMiddleware',
]

ROOT_URLCONF = 'Sphurit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # third party context processor
                'django_settings_export.settings_export',
                #custom context processor
                'teacher.context_processors.total_enroll',
                'teacher.context_processors.recent_courses',
                'teacher.context_processors.live_courses',
                'teacher.context_processors.enrolled_teachers_count', 
                'core.context_processors.topCategories',
                'core.context_processors.availableOffers',
                'core.context_processors.notification_count',
                'core.context_processors.cart_count',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'Sphurit.wsgi.application'

ASGI_APPLICATION = 'Sphurit.asgi.application'

# LEARN CHANNELS
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": ["127.0.0.1", '6379'],
#         },
#     },
# }

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
]
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfile')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTHENTICATION_BACKENDS = [
#     'core.backends.EmailPhoneUsernameAuthenticationBackend'
# ]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['TextColor', 'BGColor'],
            ['RemoveFormat', 'Source']
        ],
        'height': 500,
        
    },
}

# CRISPY_TEMPLATE_PACK = 'bootstrap4'
MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# razorpay creadentials
RAZOR_KEY_ID = 'rzp_test_e6HgqveCfjWVV7'
RAZOR_KEY_SECRET = "fJID4EhuoTfkbp2iBrpw8rcB"
# pusher creadentials
PUSHER_APP_ID = '1750673'
PUSHER_KEY = 'a900357dbf0146f8cf56'
PUSHER_SECRET = '3e45296836f813c0e6e1'
PUSHER_CLUSTER = 'ap2'


GST_RATE = 18
SETTINGS_EXPORT = ['GST_RATE']
SETTINGS_EXPORT_VARIABLE_NAME = 'public_config'

X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']

# SMTP Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'patidardharmendra830@gmail.com'  # TODO: Your email
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_PASSWORD = 'qdsi ocas abll kpqb'  # TODO: Give APP Password here
EMAIL_USE_TLS = True