# Generated by Django 4.2 on 2024-02-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatthread_message_remove_chatnotification_chat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatthread',
            options={'verbose_name': 'Workstream', 'verbose_name_plural': 'Workstreams'},
        ),
    ]
