# Generated by Django 4.2 on 2024-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatthread_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
